# Generated by Django 4.2.7 on 2025-04-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('abv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('flavor_profile', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bottle')),
            ],
        ),
        migrations.AddIndex(
            model_name='bottle',
            index=models.Index(fields=['bottle_id'], name='api_bottle_bottle__df06d2_idx'),
        ),
        migrations.AddIndex(
            model_name='bottle',
            index=models.Index(fields=['region'], name='api_bottle_region_08fcec_idx'),
        ),
        migrations.AddIndex(
            model_name='bottle',
            index=models.Index(fields=['style'], name='api_bottle_style_4ef7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='bottle',
            index=models.Index(fields=['price'], name='api_bottle_price_98baf2_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['username'], name='api_userrec_usernam_210d29_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['created_at'], name='api_userrec_created_499470_idx'),
        ),
    ]
